[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "solidity-merkle-trees/=lib/solidity-merkle-trees/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "block-hash-recorder/=lib/block-hash-recorder/src/"
]
evm_version = "prague"
via_ir = true
optimizer = true
optimizer_runs = 1000
solidity-merkle-trees = { git = "https://github.com/polytope-labs/solidity-merkle-trees" }
BlockVerifier = { git = "https://github.com/Zergity/uniswap-oracle", path = "contracts/source/BlockVerifier.sol" }

[lint]
severity = ["gas"]
exclude_lints = ["asm-keccak256"]